import { getDisabledModules } from "@/lib/config";
import type { LuxionModule, ModuleId } from "@/types/module";

const disabledModules = getDisabledModules();

const allModules = [
  {
    id: "home",
    name: "Home",
    label: "Home",
    description: "Clock, weather, search, shortcuts, and recent activity.",
    icon: "Home",
    accent: "cyan",
    status: "online",
    keywords: ["clock", "date", "weather", "stats", "shortcuts"],
    enabled: true,
  },
  {
    id: "dashboard",
    name: "Dashboard",
    label: "Dash",
    description: "A compact command center for module health and priorities.",
    icon: "LayoutDashboard",
    accent: "blue",
    status: "online",
    keywords: ["overview", "modules", "activity"],
    enabled: true,
  },
  {
    id: "homelab",
    name: "Homelab",
    label: "Lab",
    description: "Realtime CPU, RAM, disk, network, Docker, uptime, and ping data.",
    icon: "ServerCog",
    accent: "emerald",
    status: "online",
    keywords: ["cpu", "ram", "disk", "network", "docker", "ping", "uptime"],
    enabled: true,
  },
  {
    id: "notes",
    name: "Notes",
    label: "Notes",
    description: "Markdown notes with tags, categories, pinned notes, and autosave.",
    icon: "NotebookPen",
    accent: "amber",
    status: "local",
    keywords: ["markdown", "tags", "categories", "pin", "autosave"],
    enabled: true,
  },
  {
    id: "tasks",
    name: "Tasks",
    label: "Tasks",
    description: "Todos, due dates, priorities, progress, and habits.",
    icon: "ListTodo",
    accent: "rose",
    status: "local",
    keywords: ["todo", "due", "priority", "progress", "habit"],
    enabled: true,
  },
  {
    id: "files",
    name: "Files",
    label: "Files",
    description: "Upload, download, delete, folders, previews, WebP, and thumbnails.",
    icon: "FolderOpen",
    accent: "sky",
    status: "beta",
    keywords: ["upload", "download", "delete", "folder", "preview", "webp"],
    enabled: true,
  },
  {
    id: "gallery",
    name: "Gallery",
    label: "Gallery",
    description: "Albums, lazy image grid, lightbox, search, and metadata.",
    icon: "Images",
    accent: "fuchsia",
    status: "local",
    keywords: ["albums", "grid", "lightbox", "metadata", "photos"],
    enabled: true,
  },
  {
    id: "music",
    name: "Music",
    label: "Music",
    description: "FLAC-ready playlists with album art, shuffle, and repeat controls.",
    icon: "Music2",
    accent: "lime",
    status: "local",
    keywords: ["flac", "playlist", "album", "shuffle", "repeat"],
    enabled: true,
  },
  {
    id: "bookmarks",
    name: "Bookmarks",
    label: "Marks",
    description: "Categorized links with favicon fetch, search, and drag sorting.",
    icon: "Bookmark",
    accent: "orange",
    status: "local",
    keywords: ["links", "favicon", "categories", "drag", "sort"],
    enabled: true,
  },
  {
    id: "ai",
    name: "AI",
    label: "AI",
    description: "Ollama and OpenAI-compatible chat for logs, errors, scripts, and Q&A.",
    icon: "Sparkles",
    accent: "violet",
    status: "beta",
    keywords: ["ollama", "openai", "chat", "logs", "scripts", "errors"],
    enabled: true,
  },
  {
    id: "analytics",
    name: "Analytics",
    label: "Stats",
    description: "Storage, notes, files, active modules, uptime, and lightweight charts.",
    icon: "ChartNoAxesCombined",
    accent: "teal",
    status: "online",
    keywords: ["storage", "charts", "uptime", "counts"],
    enabled: true,
  },
  {
    id: "terminal",
    name: "Terminal",
    label: "Term",
    description: "Animated command overlay with local dashboard commands.",
    icon: "Terminal",
    accent: "green",
    status: "local",
    keywords: ["help", "clear", "matrix", "fortune", "neofetch"],
    enabled: true,
  },
  {
    id: "settings",
    name: "Settings",
    label: "Settings",
    description: "Theme, language, animation, backup, import, and export controls.",
    icon: "Settings",
    accent: "slate",
    status: "local",
    keywords: ["theme", "language", "backup", "import", "export"],
    enabled: true,
  },
  {
    id: "admin",
    name: "Admin",
    label: "Admin",
    description: "User management, password resets, and system overview for administrators.",
    icon: "Shield",
    accent: "emerald",
    status: "online",
    keywords: ["users", "password", "reset", "manage", "system"],
    enabled: true,
  },
] as const satisfies Array<Omit<LuxionModule, "enabled"> & { enabled: boolean }>;

export const modules: LuxionModule[] = disabledModules.size
  ? allModules.map((m) => ({
      ...m,
      enabled: !disabledModules.has(m.id),
    }))
  : allModules;

export const enabledModules = modules.filter((module) => module.enabled);

export function getModule(moduleId: ModuleId) {
  return modules.find((module) => module.id === moduleId);
}
